=== IBM-DBWKL/DBWKL/com.ibm.dbwkl/StoredProceduresSchema.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/StoredProceduresSchema"
	xmlns:spm="http://www.example.org/StoredProceduresSchema"
	elementFormDefault="qualified"
	attributeFormDefault="qualified">

	<element name="Task" >
		<complexType>
			<sequence>
				<element name="replay" type="boolean" default="false"/>
                <element name="procedure" type="spm:Procedure" minOccurs="1" maxOccurs="unbounded" />
            </sequence>
		</complexType>
	</element>

	<complexType name="Procedure">
		<sequence>
			<element name="name" type="string" minOccurs="1" />
			<element name="schema" type="string" minOccurs="0" />
			<element name="weight" minOccurs="1" type="int">

			</element>
			<element name="parameter" type="spm:Parameter" nillable="true"
				minOccurs="0" maxOccurs="unbounded" />
		</sequence>
	</complexType>

	<complexType name="Parameter">
		<sequence>
			<element name="name" type="string" minOccurs="1" />
			<element name="dataType" type="spm:ParameterDataType"
				default="integer" maxOccurs="1" minOccurs="1" />
			<element name="parmType" type="spm:ParameterType"
				default="in" minOccurs="1" maxOccurs="1"/>
			<element name="min" type="string" maxOccurs="1"
				minOccurs="0" />
			<element name="max" type="string" maxOccurs="1"
				minOccurs="0" />
			<element name="value" type="string" maxOccurs="1"
				minOccurs="0" />
			<element name="list" type="string" maxOccurs="1"
				minOccurs="0" />
			<element name="executionValue" type="string" maxOccurs="1" minOccurs="0"></element>
		</sequence>
	</complexType>

	<simpleType name="ParameterDataType">
		<restriction base="string">
			<enumeration value="integer" />
			<enumeration value="varchar" />
			<enumeration value="char" />
			<enumeration value="smallint" />
		</restriction>
	</simpleType>

	<simpleType name="ParameterType">
		<restriction base="string">
			<enumeration value="in" />
			<enumeration value="out" />
			<enumeration value="in_out" />
		</restriction>
	</simpleType>

</schema>

=== IBM-DBWKL/DBWKL/DB2WorkloadService/samples/SPMExample.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<spm:Task xmlns:spm="http://www.example.org/StoredProceduresSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/StoredProceduresSchema StoredProceduresSchema.xsd ">
    <!-- if replay true, then no randomness will be executed -->
	<spm:replay>false</spm:replay>

	<!-- procedure declaration -->
	<spm:procedure>
		<spm:name>SPNAME1</spm:name>
		<spm:schema>SPSCHEMA</spm:schema>
		<spm:weight>25</spm:weight>
	</spm:procedure>
	<spm:procedure>
		<spm:name>SPNAME2</spm:name>
		<spm:schema>SPSCHEMA</spm:schema>
		<spm:weight>50</spm:weight>
	</spm:procedure>
	<spm:procedure>
		<spm:name>SPNAME3</spm:name>
		<spm:schema>SCHEMA</spm:schema>
		<spm:weight>25</spm:weight>
		<spm:parameter>
			<spm:name>PARM1</spm:name>
			
			<!-- data type (lower case!)
				- integer
				- smallint
				- varchar
				- char
			 -->
			<spm:dataType>integer</spm:dataType>
			
			<!-- parameter type (lower case!)
			 	- in
			 	- out
			 	- in_out
			 -->
			<spm:parmType>in</spm:parmType>
			
			<!-- minimum integer/smallint value or min text
				length in case data type is char/varchar
			 -->
			<spm:min>10</spm:min>
			
			<!-- maximum integer/smallint value or max text
				length in case data type is char/varchar
			 -->
			<spm:max>100</spm:max>

			<!-- list of allowed values which takes precedence
				of minimum and maximum values
			 -->			
			<spm:list>EUR;USD;YEN</spm:list>

			<!-- hard coded value that is always used. This one
				takes precedence on any other list value or 
				random minimum/maximum values			 
			 -->
			<spm:value>value</spm:value>
		</spm:parameter>
	</spm:procedure>
</spm:Task>
